apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::398330179629:role/eksctl-demo-cluster-nodegroup-my-n-NodeInstanceRole-Kvb8Wmgb0Bos
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::398330179629:role/eks-CodeBuildServiceRole
      username: codebuild-eks

kind: ConfigMap
metadata:
  creationTimestamp: "2024-07-25T07:40:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1522"
  uid: 3b50d3fd-d58c-4116-973e-c14af875f516
